### ISSUE TITLE
Allow Operator.EQ to match nulls for Hiberate Queries

### ISSUE THREAD

**Issue by keeferrourke** [cashapp/misk#1145]
e.g. if we want to persist an object with a `String?` property and run a query that matches on that property, right now you have to do something cumbersome like this:

```kotlin
interface MaybeStringQuery: Query<DbMaybeString> {
  @Constraint(path = "maybe_string", operator = Operator.EQ)
  hasString(string: String?): MaybeStringQuery
  
  @Constraint(path = "maybe_string", operator = Operator.IS_NULL)
  nullString(): MaybeStringQuery
}

data class MaybeString(val string: String?)

...

transacter.transaction { session ->
  queryFactory.newQuery<MaybeStringQuery>()
      .apply {  // Annoying part!
        if (maybeString.string == null) nullString()
        else hasString(maybeString.string)
      }.list(session)
}
```

It would be nice if `Operator.EQ` or a new operator captured null equality as well, so we could just do `hasString(null)` to match nullable fields.

**Comment by amitdev** [comment]
Is there any objection in fixing this? We also hit similar problem in cash-idv. I think it makes sense for the `EQ` operator to generate `isNull` if the value is null. I can raise a PR for this if it sounds good.
