### ISSUE TITLE
Change Gradle compile -> api

### ISSUE THREAD

**Issue by adrw** [cashapp/misk#1343]
When you switch to the new Android Gradle plugin 3.X.X, you should replace all your compile with the implementation keyword (1*). Then try to compile and test your app. If everything it's ok leave the code as is, if you have problems you probably have something wrong with your dependencies or you used something that now is private and not more accessible. Suggestion by Android Gradle plugin engineer Jerome Dochez (1)*)

If you are a library mantainer you should use api for every dependency which is needed for the public API of your library, while use implementation for test dependencies or dependencies which must not be used by the final users.

https://stackoverflow.com/questions/44413952/gradle-implementation-vs-api-configuration

**Comment by chris-ryan-square** [comment]
https://github.com/cashapp/misk/pull/1723
