### ISSUE TITLE
Threads leak with @MiskTest(startService = false)

### ISSUE THREAD

**Issue by swankjesse** [cashapp/misk#1514]
We allow threads to be created when the `ExecutorServiceFactory` is used, even if services aren’t running in the current test. These threads are not released when the test completes because there’s no service to shut down.

**Comment by r3mariano** [comment]
I tried to shim together an alternate shutdown hook for `ExecutorServiceFactory`, but it didn't seem to alleviate memory problems.

I've also tried analysing a project when it runs tests; something else is causing thread locals to leak even with startService = true and reduced  threads (as in https://github.com/cashapp/misk/pull/1785).

**Comment by r3mariano** [comment]
Fixed the rest in https://github.com/cashapp/misk/pull/1797.
