### ISSUE TITLE
Automatically detect cloud environment and bootstrap appropriately

### ISSUE THREAD

**Issue by mmihic** [cashapp/misk#154]
``MiskApplication`` (or maybe someplace else) should automatically detect the cloud provider in which it is running and configure health systems appropriately (e.g. setup StackDriver / CloudWatch friendly logging, retrieve and cache ``InstanceMetadata``, etc). We can determine the cloud provider by hitting the provider-specific instance metadata endpoints:
 *  [AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval) - ``http://169.254.169.254/instance/latest-metadata`` 
 *  [GCP](https://cloud.google.com/compute/docs/storing-retrieving-metadata) - ``http://metadata.google.internal/computeMetadata/v1/instance``

**Comment by r3mariano** [comment]
Closing. Haven't seen a real need for this so far.

Please reopen or add a new issue if this is an enhancement that people would find useful.
