### ISSUE TITLE
QueryPager adds duplicated constraints and order

### ISSUE THREAD

**Issue by mightyguava** [cashapp/misk#1613]
Query pagination adds an additional constraint and an additional ORDER term for every page. We end up building up monster queries like

`
select dbbankingt0_.id, dbbankingt0_.customer_id, dbbankingt0_.created_at, dbbankingt0_.display_date, dbbankingt0_.merchant_id, dbbankingt0_.token, dbbankingt0_.transaction_data, dbbankingt0_.updated_at, dbbankingt0_.version 
from banking_transactions dbbankingt0_ 
where dbbankingt0_.customer_id = ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? and dbbankingt0_.id > ? 
order by dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc, dbbankingt0_.id asc 
limit ?
`

The root problem is that the `ReflectQuery` object is mutable, and constraints are added in-place. It's not trivial exactly to overwrite existing constraints, or to clone the query.

https://github.com/cashapp/misk/blob/11f53062e7131e964a934610a9b47e83bd61e7ad/misk-hibernate/src/main/kotlin/misk/hibernate/pagination/IdPaginator.kt#L31-L37

cc: @zhxnlai @swankjesse @zcross

**Comment by zcross** [comment]
Can we solve this by having the pager **compose** the underlying `ReflectionQueryFactory` and instead of updating it with `dynamicAddConstraint` over and over again, using a *copy* of the original factory? This may mean that the `QueryFactory` API forces `newPager` to be the last call in a chain of method calls to it. But that doesn't seem unnatural.

**Comment by mightyguava** [comment]
Yes, making a copy is the approach I attempted. But making a copy of a Proxy that wraps fairly complex mutable object is not so simple...
