### ISSUE TITLE
Remove FieldBinding in favour of Wire JSON support

### ISSUE THREAD

**Issue by adrw** [cashapp/misk#1634]
This file is now unnecessary and a subset of the available capabilities of Wire's Proto JSON support and should be removed.

https://github.com/cashapp/misk/blob/6a7f7cbb8d/misk/src/main/kotlin/misk/moshi/wire/FieldBinding.kt

**Comment by r3mariano** [comment]
This should be done now (https://github.com/cashapp/misk/pull/1781), next is to delete deprecated code.

**Comment by adrw** [comment]
H Y P E!
