### ISSUE TITLE
logbackClassic should maybe be exposed as a dependency from misk-testing

### ISSUE THREAD

**Issue by staktrace** [cashapp/misk#1762]
I was trying to upgrade cash-shadow to a new version of misk and it does [this thing](https://github.com/squareup/cash-shadow/blob/e3e6fd4af1602ff1b558cb3ba7256e67753e903a/testing/src/main/kotlin/com/squareup/cash/shadow/testing/ShadowTestingModule.kt#L94) which requires the logbackClassic artifact. For now I just added it to the dependencies list for cash-shadow, but it might be better fixed in misk-testing?

**Comment by chris-ryan-square** [comment]
https://github.com/cashapp/misk/pull/1768

**Comment by chris-ryan-square** [comment]
Done.

**Comment by staktrace** [comment]
Thanks!
