### ISSUE TITLE
Figure out a componentization strategy

### ISSUE THREAD

**Issue by mmihic** [cashapp/misk#179]
misk is starting to get big - it's probably about time to figure out if and how to split up into smaller source+build components. For example, we could have a structure that looks something like:

* misk-core - metrics/logging/healthchecks/tracing/startup/security + web framework
* misk-jdbc - JDBC access support
* misk-hibernate - friendly Hibernate layer
* misk-eventrouter - The eventrouter
* misk-cloud - common interfaces for cloud services
* misk-gcp - GCP-specific cloud support
* misk-aws - AWS-specific cloud support

where each is a separate buildable artifact etc

**Comment by r3mariano** [comment]
Closing. Parts of misk are now split up this way, with more to come.
