### ISSUE TITLE
Allow requests with a DELETE verb to carry a body

### ISSUE THREAD

**Issue by severb** [cashapp/misk#1917]
I'm getting this error when trying to bind a `DELETE` verb to a handler that expects a body: `cannot claim request body of DELETE`.

The error seems to originate from [here](https://github.com/cashapp/misk/blob/9593078083385e235dda816af539bd48bae616c3/misk/src/main/kotlin/misk/web/WebActionBinding.kt#L119). I propose that we remove this restriction as it's absolutely fine for `DELETE` requests to carry a body.

**Comment by r3mariano** [comment]
There was some discussion about this here: https://github.com/cashapp/misk/pull/1369#discussion_r371443935

In summary: the body of a `DELETE` request may be ignored by clients and servers, so we fail instead to remove ambiguity. This SO question has mixed opinions on it too: https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Comment by severb** [comment]
I'm not aware of any HTTP standard that disallows DELETE bodies. But you're right, I don't think this is important enough to warrant a change.
