### ISSUE TITLE
FakeMetrics breaks with multiple tests

### ISSUE THREAD

**Issue by ewolak-sq** [cashapp/misk#2001]
If I write one test class (annotated with `@MiskTest(startService = true)`) with an `@Inject lateinit var metrics: FakeMetrics` field and two `@Test` methods, the `metrics` field will get reinitialized between the first and second test _but the `FakeMetrics` injected into my service persists_. So then I'm fetching values on `metrics` and not finding them, because even in the second test they were getting recorded on the first instance of `FakeMetrics`.

**Comment by swankjesse** [comment]
After investigation we blame `companion object` and not FakeMetrics.

**Comment by ewolak-sq** [comment]
😩
