### ISSUE TITLE
Publishing is broken: 403 forbidden

### ISSUE THREAD

**Issue by shellderp** [cashapp/misk#2311]
https://github.com/cashapp/misk/runs/5453328489?check_suite_focus=true

```
Execution failed for task ':misk:publishMavenPublicationToMavenCentralRepository'.
> Failed to publish publication 'maven' to repository 'mavenCentral'
   > Could not PUT 'https://oss.sonatype.org/service/local/staging/deploy/maven2/com/squareup/misk/misk/0.23.0-20220307.1829-0f10b51/misk-0.23.0-20220307.1829-0f10b51.jar'. Received status code 403 from server: Forbidden
```

I'm not sure what changed in the last 4 months since the last successful run.

Can someone with access fix the sonatype credentials?

**Comment by r3mariano** [comment]
We should be using s01 now. Looking into it.

**Comment by shellderp** [comment]
@r3mariano thanks, I tested and the publish task succeeded. I don't see anything in the s01 sonatype staging repositories, do you see anything there?

**Comment by r3mariano** [comment]
I see a recent one, I think it's the one you published. Do you mean to publish a snapshot release?
