### ISSUE TITLE
Install a webaction shouldn’t add a dependency on WebModule

### ISSUE THREAD

**Issue by adrw** [cashapp/misk#272]
It should be possible for features like Misk’s Config to be used without a web server. But today installing any web action (such as config’s optional web admin) drags in the entire web dependency.

**Comment by swankjesse** [comment]
I believe this was fixed by this change: https://github.com/square/misk/pull/327/files

But we should write a test to confirm.

**Comment by r3mariano** [comment]
Looks resolved, closing.
