### ISSUE TITLE
DependentService dependency graph should be easier

### ISSUE THREAD

**Issue by swankjesse** [cashapp/misk#324]
Right now we’re using Guice keys to specify dependencies between services. After working with this for a while I’ve found several shortcomings:

 * I can’t declare that some other service depends on me without changing that service
 * I can’t neatly say “Jetty depends on Conscrypt but only if TLS is enabled”

I think I’d rather give the services simple string names “clock”, “jetty”, “hibernate/Movies”, “schema/Movies”, “truncate/Movies”, “conscrypt” etc. and then separately specify edges in the graph as pairs of these: [“conscrypt”, ”jetty”], [“hibernate/Movies”, “schema/Movies”]. 

I’m also tempted to make it easy to express some basic wildcards like [“clock”, “hibernate/*”], or even [“clock”, “*”].

Making this stuff foolishly-easy means application layer is easier.

I’d also like to expose this graph on the web!

**Comment by ryanhall07** [comment]
Does it make sense to start using the guava graph to start modeling this?

**Comment by swankjesse** [comment]
It's worth a look!

**Comment by keeferrourke** [comment]
#1019 has examples of the API introduced in #999 in action!

**Comment by keeferrourke** [comment]
Is this closable?

**Comment by swankjesse** [comment]
How close are we to removing the last old-style service bindings? Nuke those and then we win!

**Comment by keeferrourke** [comment]
Closing because those old-style service bindings were nuked in #1102 💥
