### ISSUE TITLE
Figure out a client strategy

### ISSUE THREAD

**Issue by mmihic** [cashapp/misk#54]
misk currently offers nothing for sending requests to other services. It should have some strategy for this, at minimum to provide a standard way to hook in cross-cutting concerns such as context propagation, end-to-end request deadlines, chain-of-trust establishment, etc. Could range from having standardized okhttp client interceptors to a full-blown stub model.

**Comment by maniksurtani** [comment]
I'd lean towards a client stub - gives us more flexibility in future with
gRPC-backed services instead of just HTTP.

**Comment by mmihic** [comment]
I lean towards that as well, but it gets a bit weird if we have a typed client stub model with e.g. proto defined service interfaces, but don't have similar server side support.

**Comment by maniksurtani** [comment]
Agreed. We could define the server-side endpoints using protos too, and generate the REST endpoints from that... that would help with consistency with paths too.
