### ISSUE TITLE
Provide dynamic flags interface

### ISSUE THREAD

**Issue by mmihic** [cashapp/misk#56]
Should provide an interface for listening / responding to dynamic flag changes. Interface probably needs to live within misk itself so misk core components can leverage it, but implementation might live elsewhere.

**Comment by mmihic** [comment]
Also should consider how flags and configuration interact (e.g. are flags a separate thing or are you listening to changes in the configuration hierarchy, should configuration itself be sourcable externally with a local cache, etc)

**Comment by maniksurtani** [comment]
+1 to making this an interface.
