### ISSUE TITLE
Tests: misk.web.ssl.PemSslClientServerTest.failsIfServerIsUntrusted() is flaky

### ISSUE THREAD

**Issue by keeferrourke** [cashapp/misk#987]
This test is flaky and apparently only reproducible on CircleCI. We think the fix might be difficult and interesting.

See lines 78-88 in `PemSslClientServerTest.kt`.

This test failed [recently](https://circleci.com/gh/square/misk/834?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with:

```
java.util.concurrent.TimeoutException: Timeout waiting for the services to stop. The following services have not stopped: {STOPPING=[JettyService [STOPPING]]}
```

**Comment by jjestrel** [comment]
this might've started happening after I bumped the jetty version

**Comment by swankjesse** [comment]
Tracking upstream: https://github.com/eclipse/jetty.project/issues/3929

**Comment by r3mariano** [comment]
Closing, this was resolved
